// <auto-generated />
using System;
using GameStore.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameStore.Api.Data.Migrations
{
    [DbContext(typeof(GameStoreContext))]
    partial class GameStoreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("GameStore.Api.Entities.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GenreId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GenreId = 1,
                            Name = "Street Fighter",
                            Price = 59.99m,
                            ReleaseDate = new DateOnly(1987, 8, 30)
                        },
                        new
                        {
                            Id = 2,
                            GenreId = 2,
                            Name = "Final Fantasy",
                            Price = 49.99m,
                            ReleaseDate = new DateOnly(1987, 12, 18)
                        },
                        new
                        {
                            Id = 3,
                            GenreId = 3,
                            Name = "FIFA 21",
                            Price = 39.99m,
                            ReleaseDate = new DateOnly(2020, 10, 9)
                        },
                        new
                        {
                            Id = 4,
                            GenreId = 4,
                            Name = "Need for Speed",
                            Price = 29.99m,
                            ReleaseDate = new DateOnly(1994, 8, 31)
                        },
                        new
                        {
                            Id = 5,
                            GenreId = 5,
                            Name = "Mario Kart",
                            Price = 19.99m,
                            ReleaseDate = new DateOnly(1992, 8, 27)
                        },
                        new
                        {
                            Id = 6,
                            GenreId = 1,
                            Name = "The Legend of Zelda",
                            Price = 59.99m,
                            ReleaseDate = new DateOnly(1986, 2, 21)
                        },
                        new
                        {
                            Id = 7,
                            GenreId = 5,
                            Name = "Super Mario Bros.",
                            Price = 49.99m,
                            ReleaseDate = new DateOnly(1985, 9, 13)
                        },
                        new
                        {
                            Id = 8,
                            GenreId = 1,
                            Name = "Halo: Combat Evolved",
                            Price = 39.99m,
                            ReleaseDate = new DateOnly(2001, 11, 15)
                        },
                        new
                        {
                            Id = 9,
                            GenreId = 2,
                            Name = "The Witcher 3: Wild Hunt",
                            Price = 59.99m,
                            ReleaseDate = new DateOnly(2015, 5, 19)
                        },
                        new
                        {
                            Id = 10,
                            GenreId = 3,
                            Name = "Minecraft",
                            Price = 26.95m,
                            ReleaseDate = new DateOnly(2011, 11, 18)
                        },
                        new
                        {
                            Id = 11,
                            GenreId = 1,
                            Name = "Overwatch",
                            Price = 39.99m,
                            ReleaseDate = new DateOnly(2016, 5, 24)
                        },
                        new
                        {
                            Id = 12,
                            GenreId = 4,
                            Name = "Red Dead Redemption 2",
                            Price = 59.99m,
                            ReleaseDate = new DateOnly(2018, 10, 26)
                        },
                        new
                        {
                            Id = 13,
                            GenreId = 2,
                            Name = "Cyberpunk 2077",
                            Price = 59.99m,
                            ReleaseDate = new DateOnly(2020, 12, 10)
                        },
                        new
                        {
                            Id = 14,
                            GenreId = 5,
                            Name = "The Sims 4",
                            Price = 39.99m,
                            ReleaseDate = new DateOnly(2014, 9, 2)
                        },
                        new
                        {
                            Id = 15,
                            GenreId = 1,
                            Name = "Fortnite",
                            Price = 0.00m,
                            ReleaseDate = new DateOnly(2017, 7, 25)
                        },
                        new
                        {
                            Id = 16,
                            GenreId = 1,
                            Name = "Call of Duty: Modern Warfare",
                            Price = 59.99m,
                            ReleaseDate = new DateOnly(2019, 10, 25)
                        },
                        new
                        {
                            Id = 17,
                            GenreId = 2,
                            Name = "Assassin's Creed Valhalla",
                            Price = 59.99m,
                            ReleaseDate = new DateOnly(2020, 11, 10)
                        },
                        new
                        {
                            Id = 18,
                            GenreId = 5,
                            Name = "Animal Crossing: New Horizons",
                            Price = 59.99m,
                            ReleaseDate = new DateOnly(2020, 3, 20)
                        },
                        new
                        {
                            Id = 19,
                            GenreId = 1,
                            Name = "Doom Eternal",
                            Price = 59.99m,
                            ReleaseDate = new DateOnly(2020, 3, 20)
                        },
                        new
                        {
                            Id = 20,
                            GenreId = 5,
                            Name = "Among Us",
                            Price = 5.00m,
                            ReleaseDate = new DateOnly(2018, 6, 15)
                        });
                });

            modelBuilder.Entity("GameStore.Api.Entities.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Fighting"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Roleplaying"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Sports"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Racing"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Kids and Family"
                        });
                });

            modelBuilder.Entity("GameStore.Api.Entities.Game", b =>
                {
                    b.HasOne("GameStore.Api.Entities.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");
                });
#pragma warning restore 612, 618
        }
    }
}
